In [1]:
import os
os.getcwd()

'c:\\Users\\Daniela\\Documents\\DataCleaningToolKit'

In [1]:
import pandas as pd
from data_cleaning_toolkit import missing_values as mv

In [2]:
data = {
        "A": [1, 2, None, 4],
        "B": [None, 2, 3, None],
        "C": [1, None, None, 4]
    }
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

print("\nSummary of Missing Values:")
print(mv.missing_values_summary(df))

print("\nFilling Missing Values (mean):")
df1 = mv.fill_missing_values(df.copy(), strategy=["mean"])
print(df1)

print("\nDropping Rows with Missing Values:")
print(mv.drop_missing_values(df1.copy(), axis=0))

Original DataFrame:
     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  NaN
3  4.0  NaN  4.0

Summary of Missing Values:
  Column  Missing Values  Percentage
0      A               1        25.0
1      B               2        50.0
2      C               2        50.0

Filling Missing Values (mean):
          A    B    C
0  1.000000  2.5  1.0
1  2.000000  2.0  2.5
2  2.333333  3.0  2.5
3  4.000000  2.5  4.0

Dropping Rows with Missing Values:
Dropping missing values...
df shape before dropping missing values: (4, 3)
df shape after dropping missing values: (4, 3)
          A    B    C
0  1.000000  2.5  1.0
1  2.000000  2.0  2.5
2  2.333333  3.0  2.5
3  4.000000  2.5  4.0

In [7]:
mv.drop_missing_values(df1.copy(), axis=0, threshold=None)

Dropping missing values...
df shape before dropping missing values: (4, 3)
df shape after dropping missing values: (0, 3)

Empty DataFrame
Columns: [A, B, C]
Index: []

In [9]:
df1.dropna(axis=0, thresh=0)

          A    B    C
0  1.000000  2.5  1.0
1  2.000000  2.0  2.5
2  2.333333  3.0  2.5
3  4.000000  2.5  4.0